-- Generated from generator/demo_specs/aws-thailand-food-export-intel.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-food-export-intel
-- This is the schema that is actually deployed for THAILAND_FOOD_EXPORT_INTEL.

-- Alerts fire on the top tail of Markets at Risk
-- (higher is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.91) WITHIN GROUP (ORDER BY KPI_MARKETS_AT_RISK) AS T
  FROM RAW.EXPORT_TRANSACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_MARKETS_AT_RISK >= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_MARKETS_AT_RISK), 2) AS AVG_MARKETS_AT_RISK,
  ROUND(AVG(f.KPI_COMPLIANCE_FLAGS), 2) AS AVG_COMPLIANCE_FLAGS,
  ROUND(AVG(f.KPI_JAPAN_DEMAND_INDEX), 2) AS AVG_JAPAN_DEMAND_INDEX,
  ROUND(AVG(f.KPI_EU_REJECTION_RATE), 2) AS AVG_EU_REJECTION_RATE
FROM RAW.EXPORT_TRANSACTIONS f
JOIN RAW.THAI_EXPORT_CONTEXT e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_MARKETS_AT_RISK), 2) AS AVG_MARKETS_AT_RISK,
  ROUND(AVG(f.KPI_COMPLIANCE_FLAGS), 2) AS AVG_COMPLIANCE_FLAGS,
  ROUND(AVG(f.KPI_JAPAN_DEMAND_INDEX), 2) AS AVG_JAPAN_DEMAND_INDEX,
  ROUND(AVG(f.KPI_EU_REJECTION_RATE), 2) AS AVG_EU_REJECTION_RATE
FROM RAW.EXPORT_TRANSACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_MARKETS_AT_RISK) AS KPI_MARKETS_AT_RISK, AVG(KPI_COMPLIANCE_FLAGS) AS KPI_COMPLIANCE_FLAGS, AVG(KPI_JAPAN_DEMAND_INDEX) AS KPI_JAPAN_DEMAND_INDEX, AVG(KPI_EU_REJECTION_RATE) AS KPI_EU_REJECTION_RATE FROM RAW.EXPORT_TRANSACTIONS),
     en AS (SELECT SUM(KPI_EXPORT_REVENUE_MTD) AS KPI_EXPORT_REVENUE_MTD, SUM(KPI_ACTIVE_SHIPMENTS) AS KPI_ACTIVE_SHIPMENTS, SUM(KPI_CHINA_TARIFF_IMPACT) AS KPI_CHINA_TARIFF_IMPACT FROM RAW.THAI_EXPORT_CONTEXT)
  SELECT 1 AS SORT_ORDER, 'Export Revenue (MTD)' AS TITLE, KPI_EXPORT_REVENUE_MTD AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_EXPORT_REVENUE_MTD) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Markets at Risk' AS TITLE, KPI_MARKETS_AT_RISK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MARKETS_AT_RISK)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Compliance Flags' AS TITLE, KPI_COMPLIANCE_FLAGS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COMPLIANCE_FLAGS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Shipments' AS TITLE, KPI_ACTIVE_SHIPMENTS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_SHIPMENTS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Japan Demand Index' AS TITLE, KPI_JAPAN_DEMAND_INDEX AS VALUE_NUM, '↑' || ' ' || TO_VARCHAR(CAST(ROUND((KPI_JAPAN_DEMAND_INDEX), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'EU Rejection Rate' AS TITLE, KPI_EU_REJECTION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EU_REJECTION_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'China Tariff Impact' AS TITLE, KPI_CHINA_TARIFF_IMPACT AS VALUE_NUM, '-' || '฿' || TO_VARCHAR(CAST(ROUND(((KPI_CHINA_TARIFF_IMPACT) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
