-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Export Market Intelligence
-- ============================================================================
USE DATABASE EXPORT_INTELLIGENCE;
USE SCHEMA ML;

-- ML.FORECAST: EXPORT_DEMAND_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.EXPORT_DEMAND_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXPORT_TRENDS'),
  SERIES_COLNAME => 'PRODUCT_MARKET',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.EXPORT_DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.EXPORT_DEMAND_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: TRADE_SHIFT_DETECTOR
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.TRADE_SHIFT_DETECTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXPORT_TRENDS'),
  SERIES_COLNAME => 'PRODUCT_MARKET',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.TRADE_SHIFT_DETECTOR_RESULTS AS
SELECT * FROM TABLE(ML.TRADE_SHIFT_DETECTOR!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXPORT_TRENDS'), SERIES_COLNAME => 'PRODUCT_MARKET', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

