-- ============================================================================
-- 99_RESET.SQL — Reset Export Market Intelligence to clean demo state
-- ============================================================================
USE DATABASE EXPORT_INTELLIGENCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_EXTRACT_SIGNALS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_OPPORTUNITIES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_BRIEFS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.MARKET_OPPORTUNITY_SCORES REFRESH;
ALTER DYNAMIC TABLE CURATED.EXPORT_TRENDS REFRESH;
ALTER DYNAMIC TABLE CURATED.TRADE_BARRIER_TRACKER REFRESH;
ALTER DYNAMIC TABLE CURATED.COMPETITIVE_POSITION REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM EXPORT_INTELLIGENCE.RAW.EXPORT_TRANSACTIONS → 350000
-- SELECT COUNT(*) FROM EXPORT_INTELLIGENCE.RAW.TRADE_SIGNALS → 80000
-- SELECT COUNT(*) FROM EXPORT_INTELLIGENCE.CURATED.MARKET_OPPORTUNITY_SCORES WHERE SCORE > 85 → 12

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_BRIEFS RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_OPPORTUNITIES RESUME;
ALTER TASK IF EXISTS APP.TASK_EXTRACT_SIGNALS RESUME;
